### ISSUE TITLE
Any chance of new version published to Hex?

### ISSUE THREAD

**Issue by scrogson** [jbrisbin/amqp_client#36]
Currently unable to use `amqp_client` with Erlang 19 when fetching from `hex`. Any chance you could publish a new release?

**Comment by arjan** [comment]
@jbrisbin friendly bump :)

**Comment by arjan** [comment]
@jbrisbin this is blocking me from publishing a package to hex... Can you please release 3.6.2 to hex.pm?
If you need any help please let me know.

**Comment by jbrisbin** [comment]
I'll try and get to this today.

**Comment by arjan** [comment]
I see that @pma and @dumbbell are the Hex.pm package owners. Maybe one of them can help out?

**Comment by dumbbell** [comment]
Hi!

Yes, @pma gave us (the RabbitMQ team) owner rights on the RabbitMQ components on Hex.pm. The goal is to integrate Hex.pm in our release build in the near future so that Hex.pm remains up-to-date. I will get to it in the coming weeks.

I will keep you posted in this issue.

**Comment by mrkaspa** [comment]
When I try the lastest version in hex it can't compile

**Comment by arjan** [comment]
welcome to the club.. :-S

**Comment by mrkaspa** [comment]
I need it to release a library based on this

**Comment by arjan** [comment]
Same here.. can't publish to hex because it has a github dependency right now :-(

**Comment by blatyo** [comment]
I published a fork of this library to hex.pm today. You can use it like this:

{:amqp_client, "3.6.2", hex: :conduit_amqp_client}

Should be a drop in replacement for the git version of 3.6.2

**Comment by arjan** [comment]
Thanks. Maybe it's good to state on Hex that it's a fork and refer to this issue. And maybe unpublish it again as soon as the RabbitMQ team has their stuff together ;-)

**Comment by dumbbell** [comment]
FYI, I started today to work on publishing the official RabbitMQ packages (`rabbit_common` and `amqp_client` for now). I need to sort out a few things because the 3rd-party Erlang.mk plugin to publish to Hex.pm seems broken or outdated. I prepared a small wrapper around rebar(1) and `rebar3_hex` to make it work with Erlang.mk. I will do more tests tomorrow and I hope to publish `rabbit_common` soon.

Note that the build tool will be GNU Make, not rebar3 so you might see some disruption in your builds if you expect a `rebar.config`.

**Comment by tonyc** [comment]
@dumbbell Thank you!!

**Comment by blatyo** [comment]
@dumbbell Thanks, looking forward to deprecating my fork

**Comment by dumbbell** [comment]
Hi everyone!

We finally published new versions of `rabbit_common` and `amqp_client`, including the documentation of `amqp_client`.

Because they use GNU Make and Erlang.mk as the build system, and because the list of files published to Hex.pm is different from previous uploaded versions, could you please give it a try and tell us if they build and work correctly for you?

**Comment by dumbbell** [comment]
Forgot to mention: the version is set to 3.6.7-pre.1 because they include commits made after 3.6.6 (including preparation for Hex.pm), but we are not yet at 3.6.7. In the future, we will only publish releases, not work in progress.
